routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();


Route::group(['namespace' => 'Blog', 'prefix' => 'blog'], function () {

    Route::resource('posts', 'PostController')->names('blog.posts');

});

//Админка блога
$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix' => 'admin/blog'
];
Route::group($groupData, function () {

    //Blog categories
    Route::resource('categories', 'CategoryController')
        ->only(['index', 'create', 'store', 'edit', 'update'])
        ->names('blog.admin.categories');
});

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Requests\BlogCategoryCreateRequest;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Models\BlogCategory;
use App\Repositories\BlogCategoryRepository;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Str;

class CategoryController extends BaseController
{

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
        $paginator = BlogCategory::paginate(15);
        return view('blog.admin.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        return view('blog.admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BlogCategoryCreateRequest $request
     * @return RedirectResponse
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();
        if (empty($data['slug'])) {
            $data['slug'] = Str::slug($data['title']);
        }

        $item = new BlogCategory($data);
        $item->save();

        if ($item) {
            return redirect()
                ->route('blog.admin.categories.edit', [$item->id])
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @param BlogCategoryRepository $blogCategoryRepository
     * @return View
     */
    public function edit($id, BlogCategoryRepository $blogCategoryRepository)
    {
        $item = $blogCategoryRepository->getEdit($id);
        if (empty($item)) {
            abort(404);
        }

        return view('blog.admin.categories.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     *
     * @return RedirectResponse
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {
        $item = BlogCategory::find($id);
        if (empty($item)) {
            return back()
                ->withErrors(['msg' => "Запись с id=[{$id}] не найдена"])
                ->withInput();
        }

        $data = $request->all();
        $result = $item
            ->fill($data)
            ->save();

        if ($result) {
            return redirect()
                ->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        }
    }
}

resources/views/blog/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')

    <form method="POST" action="{{route('blog.admin.categories.store')}}">
        @csrf
        <div class="container">

            @php
                /** @var \Illuminate\Support\ViewErrorBag $errors */
            @endphp

            @if($errors->any())
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&#9421;</span>
                            </button>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </div>
                    </div>
                </div>
            @endif

            @if(session('success'))
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&#9421;</span>
                            </button>
                            {{session()->get('success')}}
                        </div>
                    </div>
                </div>
            @endif

            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('blog.admin.categories.includes.item_edit_main_col')
                </div>
                <div class="col-md-3">
                    @include('blog.admin.categories.includes.item_edit_add_col')
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/blog/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')

    @php
        /** @var App\Models\BlogCategory $item */
    @endphp

    <form method="POST" action="{{route('blog.admin.categories.update', $item->id)}}">
        @method('PATCH')
        @csrf
        <div class="container">

            @php
                /** @var \Illuminate\Support\ViewErrorBag $errors */
            @endphp

            @if($errors->any())
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&#9421;</span>
                            </button>
                            @foreach($errors->all() as $error)
                                <li>{{$error}}</li>
                            @endforeach
                        </div>
                    </div>
                </div>
            @endif

            @if(session('success'))
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&#9421;</span>
                            </button>
                            {{session()->get('success')}}
                        </div>
                    </div>
                </div>
            @endif

            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('blog.admin.categories.includes.item_edit_main_col', ['item'=>$item])
                </div>
                <div class="col-md-3">
                    @include('blog.admin.categories.includes.item_edit_add_col', ['item'=>$item])
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/blog/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-toggeable-md navbar-light bg-faded">
                    <a class="btn btn-primary" href="{{route('blog.admin.categories.create')}}">
                        Добавить
                    </a>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <table>
                            <thead>
                            <tr>
                                <th style="width: 50px">#</th>
                                <th style="width: 250px">Категория</th>
                                <th>Родитель</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($paginator as $item)
                                @php /** @var App\Models\BlogCategory $item */ @endphp
                                <tr>
                                    <td>{{$item->id}}</td>
                                    <td>
                                        <a href="{{route('blog.admin.categories.edit', $item->id)}}">
                                            {{$item->title}}
                                        </a>
                                    </td>
                                    <td @if(in_array($item->parent_id, [0,1])) style="color: #ccc" @endif>
                                        {{$item->parent_id}}

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <br>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body text-center">
                            {{$paginator->links()}}
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection